/* eslint-disable eol-last */
/* eslint-disable comma-dangle */
/* eslint-disable quotes */
/* eslint-disable prettier/prettier */
export const Items = [
    {
        "itemId": 32592,
        "outletId": 43,
        "itemName": "Jain Special Thali",
        "itemDescription": "Paneer Veg (100g); Seasonal Veg (100g); Dal Fry (100g); Jeera Rice (150g); Butter Roti (3); Sweet (1); Salad; Pickle.",
        "categoryId": 1,
        "typeId": 2,
        "cuisineId": 3,
        "zoopPrice": 150,
        "basePrice": 220,
        "basePriceGstRate": 5,
        "basePriceGst": 11,
        "sellingPrice": 231,
        "deliveryCharge": null,
        "deliveryChargeGstRate": null,
        "deliveryChargeGst": null,
        "status": 1,
        "image": "Jain_Maharaja_Thali.jpg",
        "isFestiveItem": 0,
        "festiveStartDate": null,
        "festiveEndDate": null,
        "sortOrder": null,
        "isRecommended": 1,
        "isBestSelling": 0,
        "created": "2019-10-03T06:21:06.000Z",
        "updated": "2019-10-03T06:50:14.000Z",
        "stationCode": "NK",
        "categoryType": "Veg",
        "typeName": "Thalis",
        "irctcTypeName": "THALI",
        "cuisineName": "North Indian",
        "irctcCuisineName": "NORTH_INDIAN",
        "itemCount": 0,
        "itemTimes": [
            {
                "timeId": 21542,
                "itemId": 32592,
                "startTime": "10:30:00",
                "endTime": "22:00:00",
                "status": 1,
                "created": "2019-10-03T06:39:21.000Z",
                "updated": "2019-10-03T06:39:21.000Z",
                "stationCode": "NK"
            }
        ]
    },
    {
        "itemId": 32593,
        "outletId": 43,
        "itemName": "Veg Special Thali",
        "itemDescription": "Paneer Veg (100g); Seasonal Veg (100g); Dal Fry (100g); Jeera Rice (150g); Butter Roti (3); Raita (100g); Sweet (1); Salad; Pickle.",
        "categoryId": 1,
        "typeId": 2,
        "cuisineId": 3,
        "zoopPrice": 140,
        "basePrice": 195,
        "basePriceGstRate": 5,
        "basePriceGst": 9.75,
        "sellingPrice": 204.75,
        "deliveryCharge": null,
        "deliveryChargeGstRate": null,
        "deliveryChargeGst": null,
        "status": 1,
        "image": "Veg_Maharaja_Thali.jpg",
        "isFestiveItem": 0,
        "festiveStartDate": null,
        "festiveEndDate": null,
        "sortOrder": null,
        "isRecommended": 1,
        "isBestSelling": 0,
        "created": "2019-10-03T06:21:07.000Z",
        "updated": "2019-10-03T06:50:14.000Z",
        "stationCode": "NK",
        "categoryType": "Veg",
        "typeName": "Thalis",
        "irctcTypeName": "THALI",
        "cuisineName": "North Indian",
        "irctcCuisineName": "NORTH_INDIAN",
        "itemCount": 0,
        "itemTimes": [
            {
                "timeId": 21543,
                "itemId": 32593,
                "startTime": "10:30:00",
                "endTime": "22:00:00",
                "status": 1,
                "created": "2019-10-03T06:39:21.000Z",
                "updated": "2019-10-03T06:39:21.000Z",
                "stationCode": "NK"
            }
        ]
    },
    {
        "itemId": 32594,
        "outletId": 43,
        "itemName": "Veg Mini Thali",
        "itemDescription": "Mix Veg (100g); Dal Fry (100g); Rice (100g); Roti (3); Raita (100g); Salad; Pickle.",
        "categoryId": 1,
        "typeId": 2,
        "cuisineId": 3,
        "zoopPrice": 85,
        "basePrice": 130,
        "basePriceGstRate": 5,
        "basePriceGst": 6.5,
        "sellingPrice": 136.5,
        "deliveryCharge": null,
        "deliveryChargeGstRate": null,
        "deliveryChargeGst": null,
        "status": 1,
        "image": "Veg_Standard_Thali.jpg",
        "isFestiveItem": 0,
        "festiveStartDate": null,
        "festiveEndDate": null,
        "sortOrder": null,
        "isRecommended": 1,
        "isBestSelling": 0,
        "created": "2019-10-03T06:21:07.000Z",
        "updated": "2019-10-03T06:50:14.000Z",
        "stationCode": "NK",
        "categoryType": "Veg",
        "typeName": "Thalis",
        "irctcTypeName": "THALI",
        "cuisineName": "North Indian",
        "irctcCuisineName": "NORTH_INDIAN",
        "itemCount": 0,
        "itemTimes": [
            {
                "timeId": 21544,
                "itemId": 32594,
                "startTime": "10:30:00",
                "endTime": "22:00:00",
                "status": 1,
                "created": "2019-10-03T06:39:21.000Z",
                "updated": "2019-10-03T06:39:21.000Z",
                "stationCode": "NK"
            }
        ]
    },
    {
        "itemId": 32588,
        "outletId": 43,
        "itemName": "Veg Special Thali (10 Plates)",
        "itemDescription": "Paneer Veg (100g); Seasonal Veg (100g); Dal Fry (100g); Jeera Rice (150g); Butter Roti (3); Raita (100g); Sweet (1); Salad; Pickle.",
        "categoryId": 1,
        "typeId": 2,
        "cuisineId": 3,
        "zoopPrice": 1400,
        "basePrice": 1540,
        "basePriceGstRate": 5,
        "basePriceGst": 77,
        "sellingPrice": 1617,
        "deliveryCharge": null,
        "deliveryChargeGstRate": null,
        "deliveryChargeGst": null,
        "status": 1,
        "image": "Veg_Maharaja_Thali.jpg",
        "isFestiveItem": 0,
        "festiveStartDate": null,
        "festiveEndDate": null,
        "sortOrder": null,
        "isRecommended": 1,
        "isBestSelling": 0,
        "created": "2019-10-03T06:21:06.000Z",
        "updated": "2019-10-03T06:50:14.000Z",
        "stationCode": "NK",
        "categoryType": "Veg",
        "typeName": "Thalis",
        "irctcTypeName": "THALI",
        "cuisineName": "North Indian",
        "irctcCuisineName": "NORTH_INDIAN",
        "itemCount": 0,
        "itemTimes": [
            {
                "timeId": 21538,
                "itemId": 32588,
                "startTime": "10:30:00",
                "endTime": "22:00:00",
                "status": 1,
                "created": "2019-10-03T06:39:21.000Z",
                "updated": "2019-10-03T06:39:21.000Z",
                "stationCode": "NK"
            }
        ]
    },
    {
        "itemId": 32589,
        "outletId": 43,
        "itemName": "Veg Mini Thali (15 Plates)",
        "itemDescription": "Mix Veg (100g); Dal Fry (100g); Rice (100g); Roti (3); Raita (100g); Salad; Pickle.",
        "categoryId": 1,
        "typeId": 2,
        "cuisineId": 3,
        "zoopPrice": 1275,
        "basePrice": 1365,
        "basePriceGstRate": 5,
        "basePriceGst": 68.25,
        "sellingPrice": 1433.25,
        "deliveryCharge": null,
        "deliveryChargeGstRate": null,
        "deliveryChargeGst": null,
        "status": 1,
        "image": "Veg_Standard_Thali.jpg",
        "isFestiveItem": 0,
        "festiveStartDate": null,
        "festiveEndDate": null,
        "sortOrder": null,
        "isRecommended": 1,
        "isBestSelling": 0,
        "created": "2019-10-03T06:21:06.000Z",
        "updated": "2019-10-03T06:50:14.000Z",
        "stationCode": "NK",
        "categoryType": "Veg",
        "typeName": "Thalis",
        "irctcTypeName": "THALI",
        "cuisineName": "North Indian",
        "irctcCuisineName": "NORTH_INDIAN",
        "itemCount": 0,
        "itemTimes": [
            {
                "timeId": 21539,
                "itemId": 32589,
                "startTime": "10:30:00",
                "endTime": "22:00:00",
                "status": 1,
                "created": "2019-10-03T06:39:21.000Z",
                "updated": "2019-10-03T06:39:21.000Z",
                "stationCode": "NK"
            }
        ]
    },
    {
        "itemId": 32590,
        "outletId": 43,
        "itemName": "Jain Mini Thali (10 Plates)",
        "itemDescription": "Mix Veg (100g); Dal Fry (100g); Rice (150g); Roti (2); Salad; Pickle.",
        "categoryId": 1,
        "typeId": 2,
        "cuisineId": 3,
        "zoopPrice": 950,
        "basePrice": 1030,
        "basePriceGstRate": 5,
        "basePriceGst": 51.5,
        "sellingPrice": 1081.5,
        "deliveryCharge": null,
        "deliveryChargeGstRate": null,
        "deliveryChargeGst": null,
        "status": 1,
        "image": "Jain_Standard_Thali.jpg",
        "isFestiveItem": 0,
        "festiveStartDate": null,
        "festiveEndDate": null,
        "sortOrder": null,
        "isRecommended": 1,
        "isBestSelling": 0,
        "created": "2019-10-03T06:21:06.000Z",
        "updated": "2019-10-03T06:50:14.000Z",
        "stationCode": "NK",
        "categoryType": "Veg",
        "typeName": "Thalis",
        "irctcTypeName": "THALI",
        "cuisineName": "North Indian",
        "irctcCuisineName": "NORTH_INDIAN",
        "itemCount": 0,
        "itemTimes": [
            {
                "timeId": 21540,
                "itemId": 32590,
                "startTime": "10:30:00",
                "endTime": "22:00:00",
                "status": 1,
                "created": "2019-10-03T06:39:21.000Z",
                "updated": "2019-10-03T06:39:21.000Z",
                "stationCode": "NK"
            }
        ]
    },
    {
        "itemId": 32591,
        "outletId": 43,
        "itemName": "Jain Special Thali (6 Plates)",
        "itemDescription": "Paneer Veg (100g); Seasonal Veg (100g); Dal Fry (100g); Jeera Rice (150g); Butter Roti (3); Sweet (1); Salad; Pickle.",
        "categoryId": 1,
        "typeId": 2,
        "cuisineId": 3,
        "zoopPrice": 900,
        "basePrice": 990,
        "basePriceGstRate": 5,
        "basePriceGst": 49.5,
        "sellingPrice": 1039.5,
        "deliveryCharge": null,
        "deliveryChargeGstRate": null,
        "deliveryChargeGst": null,
        "status": 1,
        "image": "Jain_Maharaja_Thali.jpg",
        "isFestiveItem": 0,
        "festiveStartDate": null,
        "festiveEndDate": null,
        "sortOrder": null,
        "isRecommended": 1,
        "isBestSelling": 0,
        "created": "2019-10-03T06:21:06.000Z",
        "updated": "2019-10-03T06:50:14.000Z",
        "stationCode": "NK",
        "categoryType": "Veg",
        "typeName": "Thalis",
        "irctcTypeName": "THALI",
        "cuisineName": "North Indian",
        "irctcCuisineName": "NORTH_INDIAN",
        "itemCount": 0,
        "itemTimes": [
            {
                "timeId": 21541,
                "itemId": 32591,
                "startTime": "10:30:00",
                "endTime": "22:00:00",
                "status": 1,
                "created": "2019-10-03T06:39:21.000Z",
                "updated": "2019-10-03T06:39:21.000Z",
                "stationCode": "NK"
            }
        ]
    },
    {
        "itemId": 32586,
        "outletId": 43,
        "itemName": "Combo Veg Fried Rice n Manchurian",
        "itemDescription": "Veg Fried Rice (225g); Manchurian (150g)",
        "categoryId": 1,
        "typeId": 3,
        "cuisineId": 11,
        "zoopPrice": 100,
        "basePrice": 145,
        "basePriceGstRate": 5,
        "basePriceGst": 7.25,
        "sellingPrice": 152.25,
        "deliveryCharge": null,
        "deliveryChargeGstRate": null,
        "deliveryChargeGst": null,
        "status": 1,
        "image": "Fried_Rice_Manchurian.jpg",
        "isFestiveItem": 0,
        "festiveStartDate": null,
        "festiveEndDate": null,
        "sortOrder": null,
        "isRecommended": 1,
        "isBestSelling": 0,
        "created": "2019-10-03T06:21:06.000Z",
        "updated": "2019-10-03T06:50:14.000Z",
        "stationCode": "NK",
        "categoryType": "Veg",
        "typeName": "Combos",
        "irctcTypeName": "COMBO",
        "cuisineName": "Chinese",
        "irctcCuisineName": "CHINESE",
        "itemCount": 0,
        "itemTimes": [
            {
                "timeId": 21536,
                "itemId": 32586,
                "startTime": "10:30:00",
                "endTime": "22:00:00",
                "status": 1,
                "created": "2019-10-03T06:39:21.000Z",
                "updated": "2019-10-03T06:39:21.000Z",
                "stationCode": "NK"
            }
        ]
    },
    {
        "itemId": 32587,
        "outletId": 43,
        "itemName": "Combo (2) Tawa Aloo Pyaaz Paratha n Curd",
        "itemDescription": "Parantha (2); Curd (150g); Pickle.",
        "categoryId": 1,
        "typeId": 3,
        "cuisineId": 3,
        "zoopPrice": 65,
        "basePrice": 95,
        "basePriceGstRate": 5,
        "basePriceGst": 4.75,
        "sellingPrice": 99.75,
        "deliveryCharge": null,
        "deliveryChargeGstRate": null,
        "deliveryChargeGst": null,
        "status": 1,
        "image": "Aloo_Paratha_Curd.jpg",
        "isFestiveItem": 0,
        "festiveStartDate": null,
        "festiveEndDate": null,
        "sortOrder": null,
        "isRecommended": 1,
        "isBestSelling": 0,
        "created": "2019-10-03T06:21:06.000Z",
        "updated": "2019-10-03T06:50:14.000Z",
        "stationCode": "NK",
        "categoryType": "Veg",
        "typeName": "Combos",
        "irctcTypeName": "COMBO",
        "cuisineName": "North Indian",
        "irctcCuisineName": "NORTH_INDIAN",
        "itemCount": 0,
        "itemTimes": [
            {
                "timeId": 21537,
                "itemId": 32587,
                "startTime": "10:30:00",
                "endTime": "22:00:00",
                "status": 1,
                "created": "2019-10-03T06:39:21.000Z",
                "updated": "2019-10-03T06:39:21.000Z",
                "stationCode": "NK"
            }
        ]
    },
    {
        "itemId": 32576,
        "outletId": 43,
        "itemName": "Veg Fried Rice",
        "itemDescription": "300g",
        "categoryId": 1,
        "typeId": 7,
        "cuisineId": 11,
        "zoopPrice": 80,
        "basePrice": 120,
        "basePriceGstRate": 5,
        "basePriceGst": 6,
        "sellingPrice": 126,
        "deliveryCharge": null,
        "deliveryChargeGstRate": null,
        "deliveryChargeGst": null,
        "status": 1,
        "image": "Fried_Rice.jpg",
        "isFestiveItem": 0,
        "festiveStartDate": null,
        "festiveEndDate": null,
        "sortOrder": null,
        "isRecommended": 0,
        "isBestSelling": 0,
        "created": "2019-10-03T06:21:06.000Z",
        "updated": "2019-10-03T06:50:14.000Z",
        "stationCode": "NK",
        "categoryType": "Veg",
        "typeName": "Rice & Biryani",
        "irctcTypeName": "BIRYANI",
        "cuisineName": "Chinese",
        "irctcCuisineName": "CHINESE",
        "itemCount": 0,
        "itemTimes": [
            {
                "timeId": 21526,
                "itemId": 32576,
                "startTime": "10:30:00",
                "endTime": "22:00:00",
                "status": 1,
                "created": "2019-10-03T06:39:21.000Z",
                "updated": "2019-10-03T06:39:21.000Z",
                "stationCode": "NK"
            }
        ]
    },
    {
        "itemId": 32577,
        "outletId": 43,
        "itemName": "Jeera Rice",
        "itemDescription": "450g",
        "categoryId": 1,
        "typeId": 7,
        "cuisineId": 3,
        "zoopPrice": 60,
        "basePrice": 95,
        "basePriceGstRate": 5,
        "basePriceGst": 4.75,
        "sellingPrice": 99.75,
        "deliveryCharge": null,
        "deliveryChargeGstRate": null,
        "deliveryChargeGst": null,
        "status": 1,
        "image": "Jeera_Rice.jpg",
        "isFestiveItem": 0,
        "festiveStartDate": null,
        "festiveEndDate": null,
        "sortOrder": null,
        "isRecommended": 0,
        "isBestSelling": 0,
        "created": "2019-10-03T06:21:06.000Z",
        "updated": "2019-10-03T06:50:14.000Z",
        "stationCode": "NK",
        "categoryType": "Veg",
        "typeName": "Rice & Biryani",
        "irctcTypeName": "BIRYANI",
        "cuisineName": "North Indian",
        "irctcCuisineName": "NORTH_INDIAN",
        "itemCount": 0,
        "itemTimes": [
            {
                "timeId": 21527,
                "itemId": 32577,
                "startTime": "10:30:00",
                "endTime": "22:00:00",
                "status": 1,
                "created": "2019-10-03T06:39:21.000Z",
                "updated": "2019-10-03T06:39:21.000Z",
                "stationCode": "NK"
            }
        ]
    },
    {
        "itemId": 32578,
        "outletId": 43,
        "itemName": "Plain Rice",
        "itemDescription": "450g",
        "categoryId": 1,
        "typeId": 7,
        "cuisineId": 3,
        "zoopPrice": 50,
        "basePrice": 80,
        "basePriceGstRate": 5,
        "basePriceGst": 4,
        "sellingPrice": 84,
        "deliveryCharge": null,
        "deliveryChargeGstRate": null,
        "deliveryChargeGst": null,
        "status": 1,
        "image": "Steam_Rice.jpg",
        "isFestiveItem": 0,
        "festiveStartDate": null,
        "festiveEndDate": null,
        "sortOrder": null,
        "isRecommended": 0,
        "isBestSelling": 0,
        "created": "2019-10-03T06:21:06.000Z",
        "updated": "2019-10-03T06:50:14.000Z",
        "stationCode": "NK",
        "categoryType": "Veg",
        "typeName": "Rice & Biryani",
        "irctcTypeName": "BIRYANI",
        "cuisineName": "North Indian",
        "irctcCuisineName": "NORTH_INDIAN",
        "itemCount": 0,
        "itemTimes": [
            {
                "timeId": 21528,
                "itemId": 32578,
                "startTime": "10:30:00",
                "endTime": "22:00:00",
                "status": 1,
                "created": "2019-10-03T06:39:21.000Z",
                "updated": "2019-10-03T06:39:21.000Z",
                "stationCode": "NK"
            }
        ]
    },
    {
        "itemId": 32574,
        "outletId": 43,
        "itemName": "Combo Veg Biryani n Raita",
        "itemDescription": "Biryani (300g); Raita/Salad",
        "categoryId": 1,
        "typeId": 7,
        "cuisineId": 3,
        "zoopPrice": 90,
        "basePrice": 130,
        "basePriceGstRate": 5,
        "basePriceGst": 6.5,
        "sellingPrice": 136.5,
        "deliveryCharge": null,
        "deliveryChargeGstRate": null,
        "deliveryChargeGst": null,
        "status": 1,
        "image": "Biryani.jpg",
        "isFestiveItem": 0,
        "festiveStartDate": null,
        "festiveEndDate": null,
        "sortOrder": null,
        "isRecommended": 0,
        "isBestSelling": 0,
        "created": "2019-10-03T06:21:06.000Z",
        "updated": "2019-10-03T06:50:14.000Z",
        "stationCode": "NK",
        "categoryType": "Veg",
        "typeName": "Rice & Biryani",
        "irctcTypeName": "BIRYANI",
        "cuisineName": "North Indian",
        "irctcCuisineName": "NORTH_INDIAN",
        "itemCount": 0,
        "itemTimes": [
            {
                "timeId": 21524,
                "itemId": 32574,
                "startTime": "10:30:00",
                "endTime": "22:00:00",
                "status": 1,
                "created": "2019-10-03T06:39:21.000Z",
                "updated": "2019-10-03T06:39:21.000Z",
                "stationCode": "NK"
            }
        ]
    },
    {
        "itemId": 32575,
        "outletId": 43,
        "itemName": "Dal Khichadi",
        "itemDescription": "Dal Khichadi Mix (450g)",
        "categoryId": 1,
        "typeId": 7,
        "cuisineId": 3,
        "zoopPrice": 80,
        "basePrice": 120,
        "basePriceGstRate": 5,
        "basePriceGst": 6,
        "sellingPrice": 126,
        "deliveryCharge": null,
        "deliveryChargeGstRate": null,
        "deliveryChargeGst": null,
        "status": 1,
        "image": null,
        "isFestiveItem": 0,
        "festiveStartDate": null,
        "festiveEndDate": null,
        "sortOrder": null,
        "isRecommended": 0,
        "isBestSelling": 0,
        "created": "2019-10-03T06:21:06.000Z",
        "updated": "2019-10-03T06:50:14.000Z",
        "stationCode": "NK",
        "categoryType": "Veg",
        "typeName": "Rice & Biryani",
        "irctcTypeName": "BIRYANI",
        "cuisineName": "North Indian",
        "irctcCuisineName": "NORTH_INDIAN",
        "itemCount": 0,
        "itemTimes": [
            {
                "timeId": 21525,
                "itemId": 32575,
                "startTime": "10:30:00",
                "endTime": "22:00:00",
                "status": 1,
                "created": "2019-10-03T06:39:21.000Z",
                "updated": "2019-10-03T06:39:21.000Z",
                "stationCode": "NK"
            }
        ]
    },
    {
        "itemId": 32579,
        "outletId": 43,
        "itemName": "Tawa Roti Butter",
        "itemDescription": "(1pc)",
        "categoryId": 1,
        "typeId": 6,
        "cuisineId": 3,
        "zoopPrice": 15,
        "basePrice": 20,
        "basePriceGstRate": 5,
        "basePriceGst": 1,
        "sellingPrice": 21,
        "deliveryCharge": null,
        "deliveryChargeGstRate": null,
        "deliveryChargeGst": null,
        "status": 1,
        "image": "Tawa_Roti_Butter.jpg",
        "isFestiveItem": 0,
        "festiveStartDate": null,
        "festiveEndDate": null,
        "sortOrder": null,
        "isRecommended": 0,
        "isBestSelling": 0,
        "created": "2019-10-03T06:21:06.000Z",
        "updated": "2019-10-03T06:50:14.000Z",
        "stationCode": "NK",
        "categoryType": "Veg",
        "typeName": "Roti Nan Parantha",
        "irctcTypeName": "BREADS",
        "cuisineName": "North Indian",
        "irctcCuisineName": "NORTH_INDIAN",
        "itemCount": 0,
        "itemTimes": [
            {
                "timeId": 21529,
                "itemId": 32579,
                "startTime": "10:30:00",
                "endTime": "22:00:00",
                "status": 1,
                "created": "2019-10-03T06:39:21.000Z",
                "updated": "2019-10-03T06:39:21.000Z",
                "stationCode": "NK"
            }
        ]
    },
    {
        "itemId": 32580,
        "outletId": 43,
        "itemName": "Tawa Roti",
        "itemDescription": "(1pc)",
        "categoryId": 1,
        "typeId": 6,
        "cuisineId": 3,
        "zoopPrice": 12,
        "basePrice": 15,
        "basePriceGstRate": 5,
        "basePriceGst": 0.75,
        "sellingPrice": 15.75,
        "deliveryCharge": null,
        "deliveryChargeGstRate": null,
        "deliveryChargeGst": null,
        "status": 1,
        "image": "Tawa_Roti.jpg",
        "isFestiveItem": 0,
        "festiveStartDate": null,
        "festiveEndDate": null,
        "sortOrder": null,
        "isRecommended": 0,
        "isBestSelling": 0,
        "created": "2019-10-03T06:21:06.000Z",
        "updated": "2019-10-03T06:50:14.000Z",
        "stationCode": "NK",
        "categoryType": "Veg",
        "typeName": "Roti Nan Parantha",
        "irctcTypeName": "BREADS",
        "cuisineName": "North Indian",
        "irctcCuisineName": "NORTH_INDIAN",
        "itemCount": 0,
        "itemTimes": [
            {
                "timeId": 21530,
                "itemId": 32580,
                "startTime": "10:30:00",
                "endTime": "22:00:00",
                "status": 1,
                "created": "2019-10-03T06:39:21.000Z",
                "updated": "2019-10-03T06:39:21.000Z",
                "stationCode": "NK"
            }
        ]
    },
    {
        "itemId": 32584,
        "outletId": 43,
        "itemName": "Dal Fry",
        "itemDescription": "250g",
        "categoryId": 1,
        "typeId": 4,
        "cuisineId": 3,
        "zoopPrice": 70,
        "basePrice": 105,
        "basePriceGstRate": 5,
        "basePriceGst": 5.25,
        "sellingPrice": 110.25,
        "deliveryCharge": null,
        "deliveryChargeGstRate": null,
        "deliveryChargeGst": null,
        "status": 1,
        "image": "Dal_Tadka.jpg",
        "isFestiveItem": 0,
        "festiveStartDate": null,
        "festiveEndDate": null,
        "sortOrder": null,
        "isRecommended": 0,
        "isBestSelling": 0,
        "created": "2019-10-03T06:21:06.000Z",
        "updated": "2019-10-03T06:50:14.000Z",
        "stationCode": "NK",
        "categoryType": "Veg",
        "typeName": "Dal & Sabzi",
        "irctcTypeName": "MAINS",
        "cuisineName": "North Indian",
        "irctcCuisineName": "NORTH_INDIAN",
        "itemCount": 0,
        "itemTimes": [
            {
                "timeId": 21534,
                "itemId": 32584,
                "startTime": "10:30:00",
                "endTime": "22:00:00",
                "status": 1,
                "created": "2019-10-03T06:39:21.000Z",
                "updated": "2019-10-03T06:39:21.000Z",
                "stationCode": "NK"
            }
        ]
    },
    {
        "itemId": 32585,
        "outletId": 43,
        "itemName": "Jeera Aloo",
        "itemDescription": "250g",
        "categoryId": 1,
        "typeId": 4,
        "cuisineId": 3,
        "zoopPrice": 75,
        "basePrice": 105,
        "basePriceGstRate": 5,
        "basePriceGst": 5.25,
        "sellingPrice": 110.25,
        "deliveryCharge": null,
        "deliveryChargeGstRate": null,
        "deliveryChargeGst": null,
        "status": 1,
        "image": "Jeera_Aalo.jpg",
        "isFestiveItem": 0,
        "festiveStartDate": null,
        "festiveEndDate": null,
        "sortOrder": null,
        "isRecommended": 0,
        "isBestSelling": 0,
        "created": "2019-10-03T06:21:06.000Z",
        "updated": "2019-10-03T06:50:14.000Z",
        "stationCode": "NK",
        "categoryType": "Veg",
        "typeName": "Dal & Sabzi",
        "irctcTypeName": "MAINS",
        "cuisineName": "North Indian",
        "irctcCuisineName": "NORTH_INDIAN",
        "itemCount": 0,
        "itemTimes": [
            {
                "timeId": 21535,
                "itemId": 32585,
                "startTime": "10:30:00",
                "endTime": "22:00:00",
                "status": 1,
                "created": "2019-10-03T06:39:21.000Z",
                "updated": "2019-10-03T06:39:21.000Z",
                "stationCode": "NK"
            }
        ]
    },
    {
        "itemId": 32581,
        "outletId": 43,
        "itemName": "Mutter Paneer",
        "itemDescription": "450g",
        "categoryId": 1,
        "typeId": 4,
        "cuisineId": 3,
        "zoopPrice": 120,
        "basePrice": 175,
        "basePriceGstRate": 5,
        "basePriceGst": 8.75,
        "sellingPrice": 183.75,
        "deliveryCharge": null,
        "deliveryChargeGstRate": null,
        "deliveryChargeGst": null,
        "status": 1,
        "image": "Mattar_Paneer.jpg",
        "isFestiveItem": 0,
        "festiveStartDate": null,
        "festiveEndDate": null,
        "sortOrder": null,
        "isRecommended": 0,
        "isBestSelling": 0,
        "created": "2019-10-03T06:21:06.000Z",
        "updated": "2019-10-03T06:50:14.000Z",
        "stationCode": "NK",
        "categoryType": "Veg",
        "typeName": "Dal & Sabzi",
        "irctcTypeName": "MAINS",
        "cuisineName": "North Indian",
        "irctcCuisineName": "NORTH_INDIAN",
        "itemCount": 0,
        "itemTimes": [
            {
                "timeId": 21531,
                "itemId": 32581,
                "startTime": "10:30:00",
                "endTime": "22:00:00",
                "status": 1,
                "created": "2019-10-03T06:39:21.000Z",
                "updated": "2019-10-03T06:39:21.000Z",
                "stationCode": "NK"
            }
        ]
    },
    {
        "itemId": 32582,
        "outletId": 43,
        "itemName": "Paneer Butter Masala",
        "itemDescription": "450g",
        "categoryId": 1,
        "typeId": 4,
        "cuisineId": 3,
        "zoopPrice": 120,
        "basePrice": 175,
        "basePriceGstRate": 5,
        "basePriceGst": 8.75,
        "sellingPrice": 183.75,
        "deliveryCharge": null,
        "deliveryChargeGstRate": null,
        "deliveryChargeGst": null,
        "status": 1,
        "image": "Paneer_Butter_Masala.jpg",
        "isFestiveItem": 0,
        "festiveStartDate": null,
        "festiveEndDate": null,
        "sortOrder": null,
        "isRecommended": 0,
        "isBestSelling": 0,
        "created": "2019-10-03T06:21:06.000Z",
        "updated": "2019-10-03T06:50:14.000Z",
        "stationCode": "NK",
        "categoryType": "Veg",
        "typeName": "Dal & Sabzi",
        "irctcTypeName": "MAINS",
        "cuisineName": "North Indian",
        "irctcCuisineName": "NORTH_INDIAN",
        "itemCount": 0,
        "itemTimes": [
            {
                "timeId": 21532,
                "itemId": 32582,
                "startTime": "10:30:00",
                "endTime": "22:00:00",
                "status": 1,
                "created": "2019-10-03T06:39:21.000Z",
                "updated": "2019-10-03T06:39:21.000Z",
                "stationCode": "NK"
            }
        ]
    },
    {
        "itemId": 32583,
        "outletId": 43,
        "itemName": "Chana Masala",
        "itemDescription": "250g",
        "categoryId": 1,
        "typeId": 4,
        "cuisineId": 3,
        "zoopPrice": 70,
        "basePrice": 105,
        "basePriceGstRate": 5,
        "basePriceGst": 5.25,
        "sellingPrice": 110.25,
        "deliveryCharge": null,
        "deliveryChargeGstRate": null,
        "deliveryChargeGst": null,
        "status": 1,
        "image": "Channa_Masala.jpg",
        "isFestiveItem": 0,
        "festiveStartDate": null,
        "festiveEndDate": null,
        "sortOrder": null,
        "isRecommended": 0,
        "isBestSelling": 0,
        "created": "2019-10-03T06:21:06.000Z",
        "updated": "2019-10-03T06:50:14.000Z",
        "stationCode": "NK",
        "categoryType": "Veg",
        "typeName": "Dal & Sabzi",
        "irctcTypeName": "MAINS",
        "cuisineName": "North Indian",
        "irctcCuisineName": "NORTH_INDIAN",
        "itemCount": 0,
        "itemTimes": [
            {
                "timeId": 21533,
                "itemId": 32583,
                "startTime": "10:30:00",
                "endTime": "22:00:00",
                "status": 1,
                "created": "2019-10-03T06:39:21.000Z",
                "updated": "2019-10-03T06:39:21.000Z",
                "stationCode": "NK"
            }
        ]
    },
    {
        "itemId": 32570,
        "outletId": 43,
        "itemName": "Chilli Paneer Dry",
        "itemDescription": "450g",
        "categoryId": 1,
        "typeId": 8,
        "cuisineId": 11,
        "zoopPrice": 120,
        "basePrice": 175,
        "basePriceGstRate": 5,
        "basePriceGst": 8.75,
        "sellingPrice": 183.75,
        "deliveryCharge": null,
        "deliveryChargeGstRate": null,
        "deliveryChargeGst": null,
        "status": 1,
        "image": "Chilli_Paneer.jpg",
        "isFestiveItem": 0,
        "festiveStartDate": null,
        "festiveEndDate": null,
        "sortOrder": null,
        "isRecommended": 0,
        "isBestSelling": 0,
        "created": "2019-10-03T06:21:06.000Z",
        "updated": "2019-10-03T06:50:14.000Z",
        "stationCode": "NK",
        "categoryType": "Veg",
        "typeName": "Chinese",
        "irctcTypeName": "SIDES",
        "cuisineName": "Chinese",
        "irctcCuisineName": "CHINESE",
        "itemCount": 0,
        "itemTimes": [
            {
                "timeId": 21520,
                "itemId": 32570,
                "startTime": "10:30:00",
                "endTime": "22:00:00",
                "status": 1,
                "created": "2019-10-03T06:39:21.000Z",
                "updated": "2019-10-03T06:39:21.000Z",
                "stationCode": "NK"
            }
        ]
    },
    {
        "itemId": 32571,
        "outletId": 43,
        "itemName": "Chilli Paneer Gravy",
        "itemDescription": "450g",
        "categoryId": 1,
        "typeId": 8,
        "cuisineId": 11,
        "zoopPrice": 120,
        "basePrice": 175,
        "basePriceGstRate": 5,
        "basePriceGst": 8.75,
        "sellingPrice": 183.75,
        "deliveryCharge": null,
        "deliveryChargeGstRate": null,
        "deliveryChargeGst": null,
        "status": 1,
        "image": null,
        "isFestiveItem": 0,
        "festiveStartDate": null,
        "festiveEndDate": null,
        "sortOrder": null,
        "isRecommended": 0,
        "isBestSelling": 0,
        "created": "2019-10-03T06:21:06.000Z",
        "updated": "2019-10-03T06:50:14.000Z",
        "stationCode": "NK",
        "categoryType": "Veg",
        "typeName": "Chinese",
        "irctcTypeName": "SIDES",
        "cuisineName": "Chinese",
        "irctcCuisineName": "CHINESE",
        "itemCount": 0,
        "itemTimes": [
            {
                "timeId": 21521,
                "itemId": 32571,
                "startTime": "10:30:00",
                "endTime": "22:00:00",
                "status": 1,
                "created": "2019-10-03T06:39:21.000Z",
                "updated": "2019-10-03T06:39:21.000Z",
                "stationCode": "NK"
            }
        ]
    },
    {
        "itemId": 32572,
        "outletId": 43,
        "itemName": "Veg Manchurian Gravy",
        "itemDescription": "450g",
        "categoryId": 1,
        "typeId": 8,
        "cuisineId": 11,
        "zoopPrice": 100,
        "basePrice": 145,
        "basePriceGstRate": 5,
        "basePriceGst": 7.25,
        "sellingPrice": 152.25,
        "deliveryCharge": null,
        "deliveryChargeGstRate": null,
        "deliveryChargeGst": null,
        "status": 1,
        "image": "Veg_Manchurian.jpg",
        "isFestiveItem": 0,
        "festiveStartDate": null,
        "festiveEndDate": null,
        "sortOrder": null,
        "isRecommended": 0,
        "isBestSelling": 0,
        "created": "2019-10-03T06:21:06.000Z",
        "updated": "2019-10-03T06:50:14.000Z",
        "stationCode": "NK",
        "categoryType": "Veg",
        "typeName": "Chinese",
        "irctcTypeName": "SIDES",
        "cuisineName": "Chinese",
        "irctcCuisineName": "CHINESE",
        "itemCount": 0,
        "itemTimes": [
            {
                "timeId": 21522,
                "itemId": 32572,
                "startTime": "10:30:00",
                "endTime": "22:00:00",
                "status": 1,
                "created": "2019-10-03T06:39:21.000Z",
                "updated": "2019-10-03T06:39:21.000Z",
                "stationCode": "NK"
            }
        ]
    },
    {
        "itemId": 32573,
        "outletId": 43,
        "itemName": "Veg Hakka Noodles",
        "itemDescription": "300g",
        "categoryId": 1,
        "typeId": 8,
        "cuisineId": 11,
        "zoopPrice": 80,
        "basePrice": 120,
        "basePriceGstRate": 5,
        "basePriceGst": 6,
        "sellingPrice": 126,
        "deliveryCharge": null,
        "deliveryChargeGstRate": null,
        "deliveryChargeGst": null,
        "status": 1,
        "image": "Veg_Hakka_Noodles.jpg",
        "isFestiveItem": 0,
        "festiveStartDate": null,
        "festiveEndDate": null,
        "sortOrder": null,
        "isRecommended": 0,
        "isBestSelling": 0,
        "created": "2019-10-03T06:21:06.000Z",
        "updated": "2019-10-03T06:50:14.000Z",
        "stationCode": "NK",
        "categoryType": "Veg",
        "typeName": "Chinese",
        "irctcTypeName": "SIDES",
        "cuisineName": "Chinese",
        "irctcCuisineName": "CHINESE",
        "itemCount": 0,
        "itemTimes": [
            {
                "timeId": 21523,
                "itemId": 32573,
                "startTime": "10:30:00",
                "endTime": "22:00:00",
                "status": 1,
                "created": "2019-10-03T06:39:21.000Z",
                "updated": "2019-10-03T06:39:21.000Z",
                "stationCode": "NK"
            }
        ]
    },
    {
        "itemId": 32569,
        "outletId": 43,
        "itemName": "Veg Manchurian Dry",
        "itemDescription": "450g",
        "categoryId": 1,
        "typeId": 9,
        "cuisineId": 11,
        "zoopPrice": 100,
        "basePrice": 145,
        "basePriceGstRate": 5,
        "basePriceGst": 7.25,
        "sellingPrice": 152.25,
        "deliveryCharge": null,
        "deliveryChargeGstRate": null,
        "deliveryChargeGst": null,
        "status": 1,
        "image": null,
        "isFestiveItem": 0,
        "festiveStartDate": null,
        "festiveEndDate": null,
        "sortOrder": null,
        "isRecommended": 0,
        "isBestSelling": 0,
        "created": "2019-10-03T06:21:06.000Z",
        "updated": "2019-10-03T06:50:14.000Z",
        "stationCode": "NK",
        "categoryType": "Veg",
        "typeName": "Veg Starters",
        "irctcTypeName": "SNACKS",
        "cuisineName": "Chinese",
        "irctcCuisineName": "CHINESE",
        "itemCount": 0,
        "itemTimes": [
            {
                "timeId": 21519,
                "itemId": 32569,
                "startTime": "10:30:00",
                "endTime": "22:00:00",
                "status": 1,
                "created": "2019-10-03T06:39:21.000Z",
                "updated": "2019-10-03T06:39:21.000Z",
                "stationCode": "NK"
            }
        ]
    }
]

export default Items;